version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: pokemon_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pokemon_favorites
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: pokemon_user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pokemon_network

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pokemon_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: pokemon_favorites
      DB_USERNAME: pokemon_user
      DB_PASSWORD: password
    networks:
      - pokemon_network

  # Vue.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pokemon_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - pokemon_network

volumes:
  mysql_data:

networks:
  pokemon_network:
    driver: bridge
